### ISSUE TITLE
Content cards are not updating correctly on iOS when viewed on other platforms

### ISSUE THREAD

**Issue by DavidHoskinsPerkbox** [braze-inc/braze-react-sdk#178] opened 2022-10-05 10:01 UTC
Hi,

We have implemented bespoke content cards to be used on our web and native platforms. For native we are using  `requestContentCardsRefresh` to request the latest data and `addListener` to trigger updating the content cards. 

This is working as expected until we tested it on web and android and clicking on one of the content cards. When returning to the iOS platform and reloading the content cards, the `clicked` property for the content card that was clicked was coming back as `false`. To confirm the reload feature was working we sent new content cards and could see them on reload. It appears not to be updating cached content cards on iOS. This feature is working as expected on Android

**Expected result** : When clicking on a content card on one platform, this updated data would be sent to the iOS platform when requesting a refresh.

We are currently using react-native-appboy-sdk version 1.34.0

**Comment by wesleyorbin** [comment] 2022-10-05 19:51
Hi @DavidHoskinsPerkbox. Thank you for reporting this. It looks like an issue with the underlying iOS SDK. It will be fixed when we migrate to the Braze Swift SDK.

**Comment by DavidHoskinsPerkbox** [comment] 2022-10-06 13:50
Hi, do you know when you will migrate to the Braze Swift SDK?

**Comment by wesleyorbin** [comment] 2022-10-11 19:07
Hi @DavidHoskinsPerkbox. We expect to have it done by EOY. We'll update you here when it is released.

**Comment by 0mvar** [comment] 2022-11-30 23:08
dang! So it was the SDK after all. I'm facing a similar issue. 

When I send a new content card from the dashboard to an iOS device, if I call the `getRefreshedContentCards` method, it returns stale content cards. 

The only way I see the new content card is if I click the push notification from the notification center, and head back to the app inbox to refresh the feed.

```ts
export const getRefreshedContentCards = (): Promise<ContentCard[]> => {
  const req = new Promise<ContentCard[]>((resolve) => {
    const subscription = addListener(Events.CONTENT_CARDS_UPDATED, async () => {
      subscription.remove();

      resolve(await getContentCards());
    });
  });

  requestContentCardsRefresh();

  return req;
};
```

It EOY already 🫤

**Comment by Minishlink** [comment] 2023-01-04 10:35
Hello, we plan to add content cards on our app, but bug-free. Is there any ETA for a fix for this? Thanks

**Comment by hokstuff** [comment] 2023-01-04 20:46
Hi all,

Just an update on the status of the project - We are actively working on migrating the Braze React SDK to use the [new iOS Swift SDK](https://github.com/braze-inc/braze-swift-sdk/). We currently don't have an exact timeline of when the project will be completed and released. It may be in the order of months from now, but we are hoping it will be ready sooner. Once completed, we will be sure to comment on this thread.

Thank you all for your patience!

**Comment by Minishlink** [comment] 2023-01-04 23:07
Hello, thanks for your update. Is there a way to backport the fix for this issue in the Objective-C SDK from the Swift SDK?

**Comment by hokstuff** [comment] 2023-01-04 23:24
@Minishlink The Swift SDK was written from scratch, so there isn't an easy way to backport the fix into the Objective-C SDK.

**Comment by hokstuff** [comment] 2023-02-08 21:02
Hi @DavidHoskinsPerkbox @0mvar @Minishlink,

We have released the Braze React Native SDK [version 2.0.0](https://github.com/braze-inc/braze-react-sdk/releases/tag/2.0.0), which uses the new Braze Swift SDK. Let us know if you are still experiencing issues after migrating to the updated version.

You can reference [the Changelog](https://github.com/braze-inc/braze-react-sdk/blob/master/CHANGELOG.md#200) and the sample app for migration steps.

Thanks!

**Closed by hokstuff** 2023-02-08 21:02 UTC

**Comment by WojciechRupik** [comment] 2024-09-04 06:56
Same issue for 12.0.0 version :/

**Comment by hokstuff** [comment] 2024-09-04 14:36
Hi @WojciechRupik,

Since this issue is over a year old, can you contact support@braze.com with more information including specific steps to reproduce, expected vs actual behavior, relevant code snippets, and verbose logs? They will be able to help diagnose your issue better there.

Thanks!
